SELECT DISTINCT T1.CAR_ID,
       CASE
           WHEN T2.CAR_ID IS NOT NULL THEN '대여중'
           ELSE '대여 가능'
       END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
) T2 ON T1.CAR_ID = T2.CAR_ID
ORDER BY T1.CAR_ID DESC;
