WITH TotalRentalCounts AS (
    SELECT 
        CAR_ID, 
        COUNT(*) AS TOTAL_RECORDS
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY 
        CAR_ID
    HAVING 
        COUNT(*) >= 5
)
SELECT 
    CAST(DATE_FORMAT(START_DATE, '%m') AS UNSIGNED) AS MONTH, 
    T1.CAR_ID, 
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
JOIN 
    TotalRentalCounts T2 ON T1.CAR_ID = T2.CAR_ID
WHERE 
    T1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    MONTH, T1.CAR_ID
ORDER BY 
    MONTH ASC, T1.CAR_ID DESC;
