SELECT COUNT(DISTINCT T1.ID) AS FISH_COUNT, MAX(T2.LENGTH) AS MAX_LENGTH, T1.FISH_TYPE 
FROM FISH_INFO T1
JOIN (
    SELECT ID, CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END AS LENGTH
    FROM FISH_INFO
) AS T2 ON T1.ID = T2.ID
GROUP BY T1.FISH_TYPE
HAVING AVG(T2.LENGTH) >= 33
ORDER BY T1.FISH_TYPE ASC;